const LEVEL_THREE_WIDTH = 12000;
const LEVEL_THREE_GROUND = 1110;
const levelThreeAstrisImage = new Image(); levelThreeAstrisImage.src = "IMAGES/level3/astris.png";
const levelThreeSoldierImage = new Image(); levelThreeSoldierImage.src = "IMAGES/level3/enemy-soldier.png";
const levelThreeMeleeImage = new Image(); levelThreeMeleeImage.src = "IMAGES/level3/melee-soldier.png";
const levelThreeCrateImage = new Image(); levelThreeCrateImage.src = "IMAGES/level3/industrial-crate.png";
const levelThreeCartImage = new Image(); levelThreeCartImage.src = "IMAGES/level3/maintenance-cart.png";
const levelThreeRunSheet = new Image(); levelThreeRunSheet.src = "IMAGES/level3/astris-run-sheet.png";
const levelThreeIdleSheet = new Image(); levelThreeIdleSheet.src = "IMAGES/level3/astris-idle-sheet.png";
const levelThreeFactoryImage = new Image(); levelThreeFactoryImage.src = "IMAGES/level3/eclipse-factory.png";

const levelThree = { cameraX: 0, bullets: [], enemyBullets: [], enemies: [], obstacles: [], terminalX: 11550 };
const levelThreePlayer = { x: 180, y: 800, width: 118, height: 190, vx: 0, vy: 0, facing: 1, grounded: false, health: 100, shield: 100, fireCooldown: 0, damageTimer: 0, animation:"idle", animationFrame:0, animationTimer:0 };

function beginLevelThreeIntro() { gameState = GAMESTATE.LEVELTHREE_INTRO; updateMusicState(); }
function startLevelThree() {
    Object.assign(levelThreePlayer,{x:180,y:LEVEL_THREE_GROUND-190,vx:0,vy:0,facing:1,grounded:true,health:100,shield:100,fireCooldown:0,damageTimer:0,animation:"idle",animationFrame:0,animationTimer:0});
    levelThree.cameraX=0;levelThree.bullets=[];levelThree.enemyBullets=[];
    levelThree.obstacles=[1450,2700,4150,5600,7350,8900,10300].map((x,i)=>({x,y:LEVEL_THREE_GROUND-(i%2?145:110),width:i%2?150:190,height:i%2?145:110,health:10,alive:true,type:i%2?"crate":"cart"}));
    levelThree.enemies=[950,2100,3350,4800,6250,6800,8050,9550,10850].map((x,i)=>({x,y:LEVEL_THREE_GROUND-175,width:105,height:175,health:12,alive:true,cooldown:35+i*7,facing:-1,type:"rifle"}));
    levelThree.enemies.push(...[1750,3000,5200,5900,7600,8700,10100,11200].map((x,i)=>({x,y:LEVEL_THREE_GROUND-180,width:118,height:180,health:16,alive:true,cooldown:20+i*4,attackCooldown:0,facing:-1,type:"melee"})));
    gameState=GAMESTATE.LEVELTHREE;startMusic();
}
function l3Overlap(a,b){return a.x<b.x+b.width&&a.x+a.width>b.x&&a.y<b.y+b.height&&a.y+a.height>b.y;}
function damageLevelThreePlayer(amount){if(levelThreePlayer.damageTimer>0)return;const absorbed=Math.min(levelThreePlayer.shield,amount);levelThreePlayer.shield-=absorbed;levelThreePlayer.health-=amount-absorbed;levelThreePlayer.damageTimer=45;if(levelThreePlayer.health<=0)gameState=GAMESTATE.LEVELTHREE_FAILED;}
function updateLevelThree(){
    if(gameState!==GAMESTATE.LEVELTHREE)return;let move=0;if(keys.KeyQ||keys.ArrowLeft)move--;if(keys.KeyD||keys.ArrowRight)move++;move+=gamepadState.moveX;move=Math.max(-1,Math.min(1,move));
    levelThreePlayer.vx=move*8;if(Math.abs(move)>.1)levelThreePlayer.facing=Math.sign(move);
    const jump=keys.Space||keys.KeyZ||keys.ArrowUp||gamepadState.moveY<-.55||gamepadState.jump;if(jump&&levelThreePlayer.grounded){levelThreePlayer.vy=-18;levelThreePlayer.grounded=false;playTone(260,.08,.02,"square");}
    levelThreePlayer.vy+=.9;levelThreePlayer.x=Math.max(0,Math.min(LEVEL_THREE_WIDTH-levelThreePlayer.width,levelThreePlayer.x+levelThreePlayer.vx));levelThreePlayer.y+=levelThreePlayer.vy;
    if(levelThreePlayer.y+levelThreePlayer.height>=LEVEL_THREE_GROUND){levelThreePlayer.y=LEVEL_THREE_GROUND-levelThreePlayer.height;levelThreePlayer.vy=0;levelThreePlayer.grounded=true;}
    updateLevelThreePlayerAnimation(move);
    if(levelThreePlayer.damageTimer>0)levelThreePlayer.damageTimer--;else levelThreePlayer.shield=Math.min(100,levelThreePlayer.shield+.12);
    if(levelThreePlayer.fireCooldown>0)levelThreePlayer.fireCooldown--;const fire=keys.KeyF||gamepadState.frontFire;if(fire&&levelThreePlayer.fireCooldown<=0){levelThree.bullets.push({x:levelThreePlayer.x+(levelThreePlayer.facing>0?105:-10),y:levelThreePlayer.y+72,width:24,height:8,vx:levelThreePlayer.facing*19,alive:true});levelThreePlayer.fireCooldown=6;playPlayerLaserSound();}
    for(const b of levelThree.bullets){b.x+=b.vx;if(b.x<0||b.x>LEVEL_THREE_WIDTH)b.alive=false;for(const target of [...levelThree.enemies,...levelThree.obstacles])if(b.alive&&target.alive&&l3Overlap(b,target)){b.alive=false;target.health--;if(target.health<=0)target.alive=false;}}
    for(const e of levelThree.enemies){if(!e.alive)continue;e.facing=levelThreePlayer.x<e.x?-1:1;const distance=Math.abs(levelThreePlayer.x-e.x);if(e.type==="melee"){if(e.attackCooldown>0)e.attackCooldown--;if(distance<820&&distance>70)e.x+=e.facing*6.7;if(l3Overlap(levelThreePlayer,e)&&e.attackCooldown<=0){damageLevelThreePlayer(28);e.attackCooldown=55;levelThreePlayer.vx=e.facing*5;playTone(115,.16,.04,"sawtooth");}}else{if(distance<900){e.cooldown--;if(e.cooldown<=0){levelThree.enemyBullets.push({x:e.x+50,y:e.y+70,width:20,height:8,vx:e.facing*10,alive:true});e.cooldown=75;}}if(l3Overlap(levelThreePlayer,e))damageLevelThreePlayer(18);}}
    for(const b of levelThree.enemyBullets){b.x+=b.vx;if(l3Overlap(b,levelThreePlayer)){b.alive=false;damageLevelThreePlayer(15);}if(b.x<0||b.x>LEVEL_THREE_WIDTH)b.alive=false;}
    levelThree.bullets=levelThree.bullets.filter(b=>b.alive);levelThree.enemyBullets=levelThree.enemyBullets.filter(b=>b.alive);
    for(const o of levelThree.obstacles)if(o.alive&&l3Overlap(levelThreePlayer,o)){levelThreePlayer.x-=levelThreePlayer.vx;}
    levelThree.cameraX=Math.max(0,Math.min(LEVEL_THREE_WIDTH-viewport.width,levelThreePlayer.x-viewport.width*.38));if(levelThreePlayer.x>=levelThree.terminalX)gameState=GAMESTATE.LEVELTHREE_COMPLETE;
}
function updateLevelThreePlayerAnimation(move){const next=!levelThreePlayer.grounded?"jump":Math.abs(move)>.12?"run":"idle";if(next!==levelThreePlayer.animation){levelThreePlayer.animation=next;levelThreePlayer.animationFrame=0;levelThreePlayer.animationTimer=0;}if(next==="jump")return;levelThreePlayer.animationTimer++;const delay=next==="run"?5:14;if(levelThreePlayer.animationTimer>=delay){levelThreePlayer.animationTimer=0;levelThreePlayer.animationFrame=(levelThreePlayer.animationFrame+1)%(next==="run"?8:4);}}
function drawLevelThreeBackground(){ctx.fillStyle="#05070B";ctx.fillRect(0,0,viewport.width,viewport.height);if(levelThreeFactoryImage.complete){const w=1800,h=900,offset=-(levelThree.cameraX*.18%w);for(let x=offset-w;x<viewport.width+w;x+=w)ctx.drawImage(levelThreeFactoryImage,x,70,w,h);}}
function drawL3Sprite(image,o,facing=1){ctx.save();ctx.translate(o.x-levelThree.cameraX+(facing<0?o.width:0),o.y);ctx.scale(facing,1);if(image.complete)ctx.drawImage(image,0,0,o.width,o.height);else{ctx.fillStyle="#888";ctx.fillRect(0,0,o.width,o.height);}ctx.restore();}
function drawAnimatedAstris(){if(levelThreePlayer.animation==="jump"){drawL3Sprite(levelThreeAstrisImage,levelThreePlayer,levelThreePlayer.facing);return;}const running=levelThreePlayer.animation==="run";const sheet=running?levelThreeRunSheet:levelThreeIdleSheet;if(!sheet.complete||!sheet.naturalWidth){drawL3Sprite(levelThreeAstrisImage,levelThreePlayer,levelThreePlayer.facing);return;}const columns=4,rows=running?2:1,frameWidth=sheet.naturalWidth/columns,frameHeight=sheet.naturalHeight/rows,frame=levelThreePlayer.animationFrame;ctx.save();ctx.translate(levelThreePlayer.x-levelThree.cameraX+(levelThreePlayer.facing<0?levelThreePlayer.width:0),levelThreePlayer.y);ctx.scale(levelThreePlayer.facing,1);ctx.drawImage(sheet,(frame%columns)*frameWidth,Math.floor(frame/columns)*frameHeight,frameWidth,frameHeight,0,0,levelThreePlayer.width,levelThreePlayer.height);ctx.restore();}
function drawLevelThree(){drawLevelThreeBackground();ctx.save();ctx.translate(-levelThree.cameraX,0);ctx.fillStyle="#222C36";ctx.fillRect(0,LEVEL_THREE_GROUND,LEVEL_THREE_WIDTH,viewport.height-LEVEL_THREE_GROUND);ctx.strokeStyle="#ED5A34";ctx.lineWidth=5;ctx.strokeRect(0,LEVEL_THREE_GROUND,LEVEL_THREE_WIDTH,18);for(const o of levelThree.obstacles)if(o.alive){const image=o.type==="crate"?levelThreeCrateImage:levelThreeCartImage;if(image.complete&&image.naturalWidth)ctx.drawImage(image,o.x,o.y,o.width,o.height);else{ctx.fillStyle="#59616A";ctx.fillRect(o.x,o.y,o.width,o.height);}}ctx.fillStyle="#55E7FF";ctx.fillRect(levelThree.terminalX,LEVEL_THREE_GROUND-230,90,230);ctx.restore();for(const e of levelThree.enemies)if(e.alive)drawL3Sprite(e.type==="melee"?levelThreeMeleeImage:levelThreeSoldierImage,e,-e.facing);drawAnimatedAstris();ctx.save();ctx.translate(-levelThree.cameraX,0);for(const b of levelThree.bullets){ctx.fillStyle="#55DFFF";ctx.fillRect(b.x,b.y,b.width,b.height);}for(const b of levelThree.enemyBullets){ctx.fillStyle="#FF3A2E";ctx.fillRect(b.x,b.y,b.width,b.height);}ctx.restore();drawLevelThreeHud();}
function drawLevelThreeHud(){ctx.fillStyle="rgba(3,8,16,.88)";ctx.fillRect(30,25,490,130);ctx.fillStyle="#172434";ctx.fillRect(55,55,420,24);ctx.fillStyle="#55DFFF";ctx.fillRect(55,55,420*levelThreePlayer.shield/100,24);ctx.fillStyle="#172434";ctx.fillRect(55,100,420,24);ctx.fillStyle="#58D071";ctx.fillRect(55,100,420*levelThreePlayer.health/100,24);ctx.fillStyle="white";ctx.font="18px Consolas";ctx.fillText("BOUCLIER",60,50);ctx.fillText("SANTÉ",60,96);ctx.textAlign="right";ctx.fillText("RENSEIGNEMENTS  "+Math.min(100,Math.round(levelThreePlayer.x/levelThree.terminalX*100))+"%",viewport.width-45,65);}
function drawLevelThreeIntro(){drawLevelThreeBackground();ctx.fillStyle="rgba(3,8,18,.92)";ctx.fillRect(viewport.width/2-700,170,1400,920);ctx.strokeStyle="#55DFFF";ctx.strokeRect(viewport.width/2-700,170,1400,920);ctx.textAlign="center";ctx.fillStyle="#55DFFF";ctx.font="bold 60px Consolas";ctx.fillText("NIVEAU 3 — LA FORGE DE L'ÉCLIPSE",viewport.width/2,290);ctx.fillStyle="white";ctx.font="28px Consolas";["Astris a infiltré la station.","Cette usine assemble une flotte entière de cuirassés Eclipse.","Traversez les ateliers, éliminez les gardes et récupérez les renseignements.","Votre fusil est automatique et votre bouclier se régénère hors combat."].forEach((l,i)=>ctx.fillText(l,viewport.width/2,410+i*55));ctx.fillStyle="#F3C742";ctx.fillText("Q/D OU STICK — MARCHER   •   Z/ESPACE — SAUTER   •   F/GÂCHETTE — TIRER",viewport.width/2,720);ctx.fillStyle="#A7BDD0";ctx.fillText("ENTRÉE / A — COMMENCER L'INFILTRATION",viewport.width/2,830);}
function drawLevelThreeFailed(){ctx.fillStyle="rgba(0,0,0,.8)";ctx.fillRect(0,0,viewport.width,viewport.height);ctx.textAlign="center";ctx.fillStyle="#FF554C";ctx.font="bold 68px Consolas";ctx.fillText("INFILTRATION ÉCHOUÉE",viewport.width/2,viewport.height/2-60);ctx.fillStyle="white";ctx.font="25px Consolas";ctx.fillText("ENTRÉE / A — RÉESSAYER",viewport.width/2,viewport.height/2+60);}
function drawLevelThreeComplete(){drawLevelThreeBackground();ctx.fillStyle="rgba(0,0,0,.82)";ctx.fillRect(0,0,viewport.width,viewport.height);ctx.textAlign="center";ctx.fillStyle="#55E7FF";ctx.font="bold 70px Consolas";ctx.fillText("RENSEIGNEMENTS RÉCUPÉRÉS",viewport.width/2,viewport.height/2-80);ctx.fillStyle="white";ctx.font="30px Consolas";ctx.fillText("Astris détient désormais les plans de la flotte Eclipse.",viewport.width/2,viewport.height/2+10);ctx.fillText("ENTRÉE / A — PRÉPARER L'EXFILTRATION",viewport.width/2,viewport.height/2+110);}
